name: build
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  # We use the pull request number to ensure that each PR has a unique concurrency group. This prevents different PRs from interfering
  # with each other, especially when multiple PRs originate from the same branch. If the pull request number is not available, we fall
  # back to using the branch name (`github.head_ref`) or the full reference (`github.ref`), ensuring uniqueness.
  #
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "22"
          architecture: 'x64' # fix for macos-latest
          registry-url: 'https://npm.pkg.github.com'
          scope: '@plexinc'
      - name: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci
      - run: npm run preversion
